function ApplyDetailsSettings()
    local detailsSettings = {
            ["overall_clear_newtorghast"] = true,
            ["use_realtimedps"] = false,
            ["row_fade_in"] = {
                "in",
                0.2,
            },
            ["streamer_config"] = {
                ["faster_updates"] = false,
                ["quick_detection"] = false,
                ["reset_spec_cache"] = false,
                ["no_alerts"] = false,
                ["disable_mythic_dungeon"] = false,
                ["use_animation_accel"] = true,
            },
            ["all_players_are_group"] = false,
            ["use_row_animations"] = true,
            ["report_heal_links"] = false,
            ["remove_realm_from_name"] = true,
            ["minimum_overall_combat_time"] = 10,
            ["event_tracker"] = {
                ["enabled"] = false,
                ["font_color"] = {
                    1,
                    1,
                    1,
                    1,
                },
                ["show_crowdcontrol_pvm"] = false,
                ["line_color"] = {
                    0.1,
                    0.1,
                    0.1,
                    0.3,
                },
                ["font_shadow"] = "NONE",
                ["font_size"] = 10,
                ["font_face"] = "Friz Quadrata TT",
                ["line_height"] = 16,
                ["show_crowdcontrol_pvp"] = true,
                ["frame"] = {
                    ["show_title"] = true,
                    ["strata"] = "LOW",
                    ["backdrop_color"] = {
                        0.1921,
                        0.1921,
                        0.1921,
                        0.3869,
                    },
                    ["locked"] = false,
                    ["height"] = 300,
                    ["width"] = 250,
                },
                ["line_texture"] = "Details Serenity",
                ["options_frame"] = {
                },
            },
            ["report_to_who"] = "",
            ["class_specs_coords"] = {
                [62] = {
                    0.251953125,
                    0.375,
                    0.125,
                    0.25,
                },
                [1467] = {
                    0.5,
                    0.625,
                    0.5,
                    0.625,
                },
                [63] = {
                    0.375,
                    0.5,
                    0.125,
                    0.25,
                },
                [250] = {
                    0,
                    0.125,
                    0,
                    0.125,
                },
                [251] = {
                    0.125,
                    0.25,
                    0,
                    0.125,
                },
                [252] = {
                    0.25,
                    0.375,
                    0,
                    0.125,
                },
                [1468] = {
                    0.625,
                    0.75,
                    0.5,
                    0.625,
                },
                [253] = {
                    0.875,
                    1,
                    0,
                    0.125,
                },
                [254] = {
                    0,
                    0.125,
                    0.125,
                    0.25,
                },
                [255] = {
                    0.125,
                    0.25,
                    0.125,
                    0.25,
                },
                [66] = {
                    0.125,
                    0.25,
                    0.25,
                    0.375,
                },
                [257] = {
                    0.5,
                    0.625,
                    0.25,
                    0.375,
                },
                [258] = {
                    0.6328125,
                    0.75,
                    0.25,
                    0.375,
                },
                [259] = {
                    0.125,
                    0.25,
                    0.75,
                    0.875,
                },
                [260] = {
                    0,
                    0.125,
                    0.75,
                    0.875,
                },
                [577] = {
                    0.25,
                    0.375,
                    0.5,
                    0.625,
                },
                [262] = {
                    0.125,
                    0.25,
                    0.375,
                    0.5,
                },
                [581] = {
                    0.375,
                    0.5,
                    0.5,
                    0.625,
                },
                [264] = {
                    0.375,
                    0.5,
                    0.375,
                    0.5,
                },
                [265] = {
                    0.5,
                    0.625,
                    0.375,
                    0.5,
                },
                [266] = {
                    0.625,
                    0.75,
                    0.375,
                    0.5,
                },
                [267] = {
                    0.75,
                    0.875,
                    0.375,
                    0.5,
                },
                [268] = {
                    0.625,
                    0.75,
                    0.125,
                    0.25,
                },
                [269] = {
                    0.875,
                    1,
                    0.125,
                    0.25,
                },
                [270] = {
                    0.75,
                    0.875,
                    0.125,
                    0.25,
                },
                [70] = {
                    0.251953125,
                    0.375,
                    0.25,
                    0.375,
                },
                [102] = {
                    0.375,
                    0.5,
                    0,
                    0.125,
                },
                [71] = {
                    0.875,
                    1,
                    0.375,
                    0.5,
                },
                [103] = {
                    0.5,
                    0.625,
                    0,
                    0.125,
                },
                [72] = {
                    0,
                    0.125,
                    0.5,
                    0.625,
                },
                [104] = {
                    0.625,
                    0.75,
                    0,
                    0.125,
                },
                [64] = {
                    0.5,
                    0.625,
                    0.125,
                    0.25,
                },
                [73] = {
                    0.125,
                    0.25,
                    0.5,
                    0.625,
                },
                [65] = {
                    0,
                    0.125,
                    0.25,
                    0.375,
                },
                [105] = {
                    0.75,
                    0.875,
                    0,
                    0.125,
                },
                [256] = {
                    0.375,
                    0.5,
                    0.25,
                    0.375,
                },
                [261] = {
                    0,
                    0.125,
                    0.375,
                    0.5,
                },
                [263] = {
                    0.25,
                    0.375,
                    0.375,
                    0.5,
                },
                [1473] = {
                    0.75,
                    0.875,
                    0.5,
                    0.625,
                },
            },
            ["all_in_one_windows"] = {
            },
            ["tooltip"] = {
                ["tooltip_max_abilities"] = 8,
                ["bar_color"] = {
                    0.396,
                    0.396,
                    0.396,
                    0.87,
                },
                ["tooltip_max_pets"] = 2,
                ["abbreviation"] = 2,
                ["header_text_color"] = {
                    1,
                    0.9176,
                    0,
                    1,
                },
                ["background"] = {
                    0.0941,
                    0.0941,
                    0.0941,
                    0.8,
                },
                ["rounded_corner"] = true,
                ["divisor_color"] = {
                    1,
                    1,
                    1,
                    1,
                },
                ["fontshadow"] = false,
                ["anchor_screen_pos"] = {
                    507.7,
                    -350.5,
                },
                ["header_statusbar"] = {
                    0.3,
                    0.3,
                    0.3,
                    0.8,
                    false,
                    false,
                    "WorldState Score",
                },
                ["fontcolor_right"] = {
                    1,
                    0.7,
                    0,
                    1,
                },
                ["line_height"] = 17,
                ["tooltip_max_targets"] = 2,
                ["icon_size"] = {
                    ["W"] = 17,
                    ["H"] = 17,
                },
                ["anchor_relative"] = "top",
                ["anchored_to"] = 1,
                ["show_amount"] = false,
                ["submenu_wallpaper"] = true,
                ["fontsize_title"] = 10,
                ["commands"] = {
                },
                ["fontface"] = "Friz Quadrata TT",
                ["border_color"] = {
                    0,
                    0,
                    0,
                    1,
                },
                ["border_texture"] = "Details BarBorder 3",
                ["menus_bg_texture"] = "Interface\\SPELLBOOK\\Spellbook-Page-1",
                ["fontcolor"] = {
                    1,
                    1,
                    1,
                    1,
                },
                ["fontsize"] = 10,
                ["border_size"] = 14,
                ["maximize_method"] = 1,
                ["anchor_offset"] = {
                    0,
                    0,
                },
                ["anchor_point"] = "bottom",
                ["menus_bg_coords"] = {
                    0.309777336120606,
                    0.924000015258789,
                    0.213000011444092,
                    0.279000015258789,
                },
                ["icon_border_texcoord"] = {
                    ["R"] = 0.921875,
                    ["L"] = 0.078125,
                    ["T"] = 0.078125,
                    ["B"] = 0.921875,
                },
                ["menus_bg_color"] = {
                    0.8,
                    0.8,
                    0.8,
                    0.2,
                },
            },
            ["ps_abbreviation"] = 3,
            ["world_combat_is_trash"] = false,
            ["pvp_as_group"] = true,
            ["bookmark_text_size"] = 11,
            ["animation_speed_mintravel"] = 0.45,
            ["track_item_level"] = false,
            ["fade_speed"] = 0.15,
            ["death_tooltip_spark"] = false,
            ["windows_fade_in"] = {
                "in",
                0.2,
            },
            ["instances_menu_click_to_open"] = false,
            ["overall_clear_newchallenge"] = true,
            ["use_self_color"] = false,
            ["data_cleanup_logout"] = false,
            ["instances_disable_bar_highlight"] = false,
            ["grouping_horizontal_gap"] = 0,
            ["death_log_colors"] = {
                ["debuff"] = "purple",
                ["buff"] = "silver",
                ["friendlyfire"] = "darkorange",
                ["heal"] = "green",
                ["cooldown"] = "yellow",
                ["damage"] = "red",
            },
            ["deadlog_limit"] = 16,
            ["trash_concatenate"] = false,
            ["deny_score_messages"] = false,
            ["instances_segments_locked"] = true,
            ["use_battleground_server_parser"] = false,
            ["animation_speed"] = 33,
            ["data_broker_text"] = "",
            ["standard_skin"] = false,
            ["disable_lock_ungroup_buttons"] = false,
            ["memory_ram"] = 64,
            ["instances_no_libwindow"] = false,
            ["clear_ungrouped"] = true,
            ["disable_window_groups"] = false,
            ["numerical_system_symbols"] = "auto",
            ["report_schema"] = 1,
            ["instances_suppress_trash"] = 0,
            ["update_speed"] = 0.2,
            ["options_window"] = {
                ["scale"] = 1,
            },
            ["animation_speed_maxtravel"] = 3,
            ["time_type"] = 2,
            ["numerical_system"] = 1,
            ["font_faces"] = {
                ["menus"] = "Friz Quadrata TT",
            },
            ["row_fade_out"] = {
                "out",
                0.2,
            },
            ["show_arena_role_icon"] = false,
            ["overall_clear_pvp"] = true,
            ["segments_amount"] = 25,
            ["report_lines"] = 5,
            ["overall_flag"] = 16,
            ["windows_fade_out"] = {
                "out",
                0.2,
            },
            ["skin"] = "Minimalistic",
            ["override_spellids"] = true,
            ["use_scroll"] = false,
            ["color_by_arena_team"] = true,
            ["overall_clear_logout"] = false,
            ["new_window_size"] = {
                ["height"] = 158,
                ["width"] = 310,
            },
            ["realtimedps_always_arena"] = false,
            ["font_sizes"] = {
                ["menus"] = 10,
            },
            ["cloud_capture"] = true,
            ["damage_taken_everything"] = false,
            ["scroll_speed"] = 2,
            ["window_clamp"] = {
                -8,
                0,
                21,
                -14,
            },
            ["memory_threshold"] = 3,
            ["deadlog_events"] = 32,
            ["default_bg_color"] = 0.0941,
            ["close_shields"] = false,
            ["class_coords"] = {
                ["HUNTER"] = {
                    0,
                    0.125,
                    0.125,
                    0.25,
                },
                ["WARRIOR"] = {
                    0,
                    0.125,
                    0,
                    0.125,
                },
                ["SHAMAN"] = {
                    0.125,
                    0.248046875,
                    0.125,
                    0.25,
                },
                ["MAGE"] = {
                    0.125,
                    0.248046875,
                    0,
                    0.125,
                },
                ["PET"] = {
                    0.125,
                    0.248046875,
                    0.375,
                    0.5,
                },
                ["DRUID"] = {
                    0.37109375,
                    0.494140625,
                    0,
                    0.125,
                },
                ["MONK"] = {
                    0.25,
                    0.369140625,
                    0.25,
                    0.375,
                },
                ["DEATHKNIGHT"] = {
                    0.125,
                    0.25,
                    0.25,
                    0.375,
                },
                ["UNGROUPPLAYER"] = {
                    0.25,
                    0.375,
                    0.375,
                    0.5,
                },
                ["PALADIN"] = {
                    0,
                    0.125,
                    0.25,
                    0.375,
                },
                ["UNKNOW"] = {
                    0.25,
                    0.375,
                    0.375,
                    0.5,
                },
                ["PRIEST"] = {
                    0.248046875,
                    0.37109375,
                    0.125,
                    0.25,
                },
                ["ENEMY"] = {
                    0,
                    0.125,
                    0.375,
                    0.5,
                },
                ["Alliance"] = {
                    0.248046875,
                    0.02968748,
                    0.375,
                    0.5,
                },
                ["WARLOCK"] = {
                    0.37109375,
                    0.494140625,
                    0.125,
                    0.25,
                },
                ["DEMONHUNTER"] = {
                    0.36914063,
                    0.5,
                    0.25,
                    0.375,
                },
                ["Horde"] = {
                    0.37109375,
                    0.494140625,
                    0.375,
                    0.5,
                },
                ["ROGUE"] = {
                    0.248046875,
                    0.37109375,
                    0,
                    0.125,
                },
                ["EVOKER"] = {
                    0.50390625,
                    0.625,
                    0,
                    0.125,
                },
                ["MONSTER"] = {
                    0,
                    0.125,
                    0.375,
                    0.5,
                },
            },
            ["hotcorner_topleft"] = {
                ["hide"] = false,
            },
            ["disable_alldisplays_window"] = false,
            ["class_colors"] = {
                ["HUNTER"] = {
                    0.67,
                    0.83,
                    0.45,
                },
                ["WARRIOR"] = {
                    0.78,
                    0.61,
                    0.43,
                },
                ["SHAMAN"] = {
                    0,
                    0.44,
                    0.87,
                },
                ["MAGE"] = {
                    0.41,
                    0.8,
                    0.94,
                },
                ["ARENA_YELLOW"] = {
                    1,
                    1,
                    0.25,
                },
                ["UNGROUPPLAYER"] = {
                    0.4,
                    0.4,
                    0.4,
                },
                ["DRUID"] = {
                    1,
                    0.49,
                    0.04,
                },
                ["MONK"] = {
                    0,
                    1,
                    0.59,
                },
                ["DEATHKNIGHT"] = {
                    0.77,
                    0.12,
                    0.23,
                },
                ["PALADIN"] = {
                    0.96,
                    0.55,
                    0.73,
                },
                ["ARENA_GREEN"] = {
                    0.686,
                    0.372,
                    0.905,
                },
                ["ROGUE"] = {
                    1,
                    0.96,
                    0.41,
                },
                ["UNKNOW"] = {
                    0.2,
                    0.2,
                    0.2,
                },
                ["PRIEST"] = {
                    1,
                    1,
                    1,
                },
                ["WARLOCK"] = {
                    0.58,
                    0.51,
                    0.79,
                },
                ["version"] = 1,
                ["ENEMY"] = {
                    0.94117,
                    0,
                    0.0196,
                    1,
                },
                ["DEMONHUNTER"] = {
                    0.64,
                    0.19,
                    0.79,
                },
                ["PET"] = {
                    0.3,
                    0.4,
                    0.5,
                },
                ["NEUTRAL"] = {
                    1,
                    1,
                    0,
                },
                ["EVOKER"] = {
                    0.2,
                    0.5764,
                    0.498,
                },
                ["SELF"] = {
                    0.89019,
                    0.32156,
                    0.89019,
                },
            },
            ["segments_amount_to_save"] = 15,
            ["trash_auto_remove"] = false,
            ["animation_speed_triggertravel"] = 5,
            ["clear_graphic"] = true,
            ["total_abbreviation"] = 2,
            ["segments_auto_erase"] = 1,
            ["options_group_edit"] = true,
            ["broadcaster_enabled"] = false,
            ["minimap"] = {
                ["onclick_what_todo"] = 1,
                ["radius"] = 160,
                ["hide"] = false,
                ["minimapPos"] = 220,
                ["text_format"] = 3,
                ["text_type"] = 1,
            },
            ["instances_amount"] = 5,
            ["max_window_size"] = {
                ["height"] = 450,
                ["width"] = 480,
            },
            ["chat_tab_embed"] = {
                ["enabled"] = false,
                ["y_offset"] = 0,
                ["x_offset"] = 0,
                ["tab_name"] = "",
                ["single_window"] = false,
            },
            ["only_pvp_frags"] = false,
            ["disable_stretch_button"] = false,
            ["minimum_combat_time"] = 5,
            ["capture_real"] = {
                ["heal"] = true,
                ["spellcast"] = true,
                ["miscdata"] = true,
                ["aura"] = true,
                ["energy"] = true,
                ["damage"] = true,
            },
            ["overall_clear_newboss"] = true,
            ["segments_panic_mode"] = false,
            ["realtimedps_order_bars"] = false,
            ["instances"] = {
                {
                    ["__pos"] = {
                        ["normal"] = {
                            ["y"] = -538.0547370910645,
                            ["x"] = 604.1561279296875,
                            ["w"] = 182.7776947021484,
                            ["h"] = 107.4443588256836,
                        },
                        ["solo"] = {
                            ["y"] = 2,
                            ["x"] = 1,
                            ["w"] = 300,
                            ["h"] = 200,
                        },
                    },
                    ["hide_in_combat_type"] = 1,
                    ["menu_icons_size"] = 0.82,
                    ["titlebar_shown"] = false,
                    ["menu_anchor"] = {
                        20,
                        0,
                        ["side"] = 2,
                    },
                    ["bg_r"] = 0.2431372702121735,
                    ["fullborder_size"] = 0.5,
                    ["hide_out_of_combat"] = false,
                    ["color_buttons"] = {
                        1,
                        1,
                        1,
                        1,
                    },
                    ["toolbar_icon_file"] = "Interface\\AddOns\\Details\\images\\toolbar_icons_2_shadow",
                    ["bars_sort_direction"] = 1,
                    ["use_auto_align_multi_fontstrings"] = true,
                    ["rowareaborder_shown"] = false,
                    ["fullborder_shown"] = false,
                    ["clickthrough_toolbaricons"] = false,
                    ["clickthrough_rows"] = false,
                    ["titlebar_texture"] = "Details Serenity",
                    ["ignore_mass_showhide"] = false,
                    ["plugins_grow_direction"] = 1,
                    ["icon_desaturated"] = false,
                    ["switch_damager"] = false,
                    ["micro_displays_side"] = 2,
                    ["window_scale"] = 1,
                    ["attribute_icon_size"] = 0,
                    ["hide_icon"] = true,
                    ["toolbar_side"] = 1,
                    ["fullborder_color"] = {
                        0,
                        0,
                        0,
                        1,
                    },
                    ["menu_icons_alpha"] = 0.92,
                    ["bg_b"] = 0.2588235437870026,
                    ["switch_healer_in_combat"] = false,
                    ["color"] = {
                        0.1215686351060867,
                        0.1176470667123795,
                        0.1294117718935013,
                        0,
                    },
                    ["hide_on_context"] = {
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                    },
                    ["desaturated_menu"] = false,
                    ["use_multi_fontstrings"] = true,
                    ["__was_opened"] = true,
                    ["switch_all_roles_in_combat"] = false,
                    ["skin"] = "Minimalistic",
                    ["total_bar"] = {
                        ["enabled"] = false,
                        ["only_in_group"] = true,
                        ["icon"] = "Interface\\ICONS\\INV_Sigil_Thorim",
                        ["color"] = {
                            1,
                            1,
                            1,
                        },
                    },
                    ["following"] = {
                        ["enabled"] = true,
                        ["bar_color"] = {
                            1,
                            1,
                            1,
                        },
                        ["text_color"] = {
                            1,
                            1,
                            1,
                        },
                    },
                    ["backdrop_texture"] = "Details Ground",
                    ["switch_healer"] = false,
                    ["fontstrings_text2_anchor"] = 73,
                    ["bars_inverted"] = false,
                    ["menu_icons"] = {
                        true,
                        true,
                        true,
                        true,
                        true,
                        false,
                        ["space"] = -2,
                        ["shadow"] = false,
                    },
                    ["attribute_text"] = {
                        ["enabled"] = true,
                        ["shadow"] = false,
                        ["side"] = 1,
                        ["text_size"] = 11,
                        ["custom_text"] = "{name}",
                        ["show_timer_arena"] = true,
                        ["text_face"] = "Accidental Presidency",
                        ["show_timer_always"] = true,
                        ["text_color"] = {
                            1,
                            1,
                            1,
                            1,
                        },
                        ["anchor"] = {
                            -17,
                            2,
                        },
                        ["show_timer"] = true,
                        ["enable_custom_text"] = false,
                        ["show_timer_bg"] = true,
                    },
                    ["show_sidebars"] = false,
                    ["switch_tank_in_combat"] = false,
                    ["StatusBarSaved"] = {
                        ["options"] = {
                            ["DETAILS_STATUSBAR_PLUGIN_PDPS"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["textXMod"] = 0,
                                ["textFace"] = "Accidental Presidency",
                                ["textAlign"] = 3,
                                ["textStyle"] = 2,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                            ["DETAILS_STATUSBAR_PLUGIN_PSEGMENT"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["segmentType"] = 2,
                                ["textFace"] = "Accidental Presidency",
                                ["textXMod"] = 0,
                                ["textAlign"] = 1,
                                ["textStyle"] = 2,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                            ["DETAILS_STATUSBAR_PLUGIN_CLOCK"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["textFace"] = "Accidental Presidency",
                                ["textXMod"] = 6,
                                ["textAlign"] = 2,
                                ["textStyle"] = 2,
                                ["timeType"] = 1,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                        },
                        ["right"] = "DETAILS_STATUSBAR_PLUGIN_PDPS",
                        ["left"] = "DETAILS_STATUSBAR_PLUGIN_PSEGMENT",
                        ["center"] = "DETAILS_STATUSBAR_PLUGIN_CLOCK",
                    },
                    ["bg_alpha"] = 0,
                    ["__snapH"] = true,
                    ["instance_button_anchor"] = {
                        -27,
                        1,
                    },
                    ["version"] = 3,
                    ["fontstrings_text4_anchor"] = 0,
                    ["__locked"] = true,
                    ["menu_alpha"] = {
                        ["enabled"] = false,
                        ["onleave"] = 1,
                        ["ignorebars"] = false,
                        ["iconstoo"] = true,
                        ["onenter"] = 1,
                    },
                    ["show_statusbar"] = false,
                    ["switch_tank"] = false,
                    ["skin_custom"] = "",
                    ["rowareaborder_size"] = 0.5,
                    ["clickthrough_incombatonly"] = true,
                    ["__snap"] = {
                        [3] = 2,
                    },
                    ["grab_on_top"] = false,
                    ["hide_in_combat_alpha"] = 0,
                    ["bars_grow_direction"] = 1,
                    ["rounded_corner_enabled"] = false,
                    ["libwindow"] = {
                        ["y"] = 8.223082542419434,
                        ["x"] = -371.1217041015625,
                        ["point"] = "BOTTOMRIGHT",
                        ["scale"] = 1,
                    },
                    ["statusbar_info"] = {
                        ["alpha"] = 0,
                        ["overlay"] = {
                            0.1215686351060867,
                            0.1176470667123795,
                            0.1294117718935013,
                        },
                    },
                    ["menu_anchor_down"] = {
                        16,
                        -3,
                    },
                    ["row_show_animation"] = {
                        ["anim"] = "Fade",
                        ["options"] = {
                        },
                    },
                    ["rowareaborder_color"] = {
                        0,
                        0,
                        0,
                        1,
                    },
                    ["strata"] = "LOW",
                    ["row_info"] = {
                        ["show_arena_role_icon"] = false,
                        ["spec_file"] = "Interface\\AddOns\\Details\\images\\spec_icons_normal",
                        ["textL_outline"] = false,
                        ["row_offsets"] = {
                            ["top"] = 0,
                            ["right"] = 0,
                            ["left"] = 0,
                            ["bottom"] = 0,
                        },
                        ["textR_outline_small"] = true,
                        ["textR_show_data"] = {
                            true,
                            true,
                            false,
                        },
                        ["percent_type"] = 1,
                        ["fixed_text_color"] = {
                            1,
                            1,
                            1,
                        },
                        ["textL_offset"] = 0,
                        ["text_yoffset"] = 0,
                        ["texture_background_class_color"] = false,
                        ["textL_outline_small_color"] = {
                            0,
                            0,
                            0,
                            1,
                        },
                        ["font_face_file"] = "Interface\\Addons\\Plater\\fonts\\Accidental Presidency.ttf",
                        ["faction_icon_size_offset"] = -10,
                        ["textL_custom_text"] = "{data1}. {data3}{data2}",
                        ["backdrop"] = {
                            ["color"] = {
                                1,
                                1,
                                1,
                                1,
                            },
                            ["texture"] = "Details BarBorder 2",
                            ["enabled"] = false,
                            ["size"] = 12,
                        },
                        ["font_size"] = 10,
                        ["models"] = {
                            ["upper_model"] = "Spells\\AcidBreath_SuperGreen.M2",
                            ["lower_model"] = "World\\EXPANSION02\\DOODADS\\Coldarra\\COLDARRALOCUS.m2",
                            ["upper_alpha"] = 0.5,
                            ["lower_enabled"] = false,
                            ["lower_alpha"] = 0.1,
                            ["upper_enabled"] = false,
                        },
                        ["start_after_icon"] = false,
                        ["height"] = 18,
                        ["textL_translit_text"] = false,
                        ["texture_custom_file"] = "Interface\\",
                        ["texture_file"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Statusbar_Clean",
                        ["icon_size_offset"] = 0,
                        ["textL_outline_small"] = true,
                        ["icon_mask"] = "",
                        ["overlay_color"] = {
                            0.7,
                            0.7,
                            0.7,
                            0,
                        },
                        ["textR_outline"] = false,
                        ["use_spec_icons"] = false,
                        ["arena_role_icon_size_offset"] = -10,
                        ["icon_grayscale"] = false,
                        ["textR_enable_custom_text"] = false,
                        ["textR_bracket"] = "(",
                        ["texture_custom"] = "",
                        ["textL_class_colors"] = false,
                        ["fixed_texture_color"] = {
                            0,
                            0,
                            0,
                        },
                        ["textL_show_number"] = false,
                        ["alpha"] = 1,
                        ["texture_background"] = "Clean",
                        ["textR_custom_text"] = "{data1} ({data2}, {data3}%)",
                        ["texture"] = "Clean",
                        ["space"] = {
                            ["right"] = 0,
                            ["left"] = 0,
                            ["between"] = 2,
                        },
                        ["fixed_texture_background_color"] = {
                            0,
                            0,
                            0,
                            0.150228589773178,
                        },
                        ["overlay_texture"] = "Clean",
                        ["texture_background_file"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Statusbar_Clean",
                        ["texture_highlight"] = "Interface\\FriendsFrame\\UI-FriendsList-Highlight",
                        ["textR_class_colors"] = false,
                        ["textR_outline_small_color"] = {
                            0,
                            0,
                            0,
                            1,
                        },
                        ["no_icon"] = true,
                        ["icon_offset"] = {
                            0,
                            0,
                        },
                        ["icon_file"] = "",
                        ["font_face"] = "Accidental Presidency",
                        ["texture_class_colors"] = true,
                        ["show_faction_icon"] = false,
                        ["fast_ps_update"] = false,
                        ["textR_separator"] = "NONE",
                        ["textL_enable_custom_text"] = false,
                    },
                    ["switch_damager_in_combat"] = false,
                    ["switch_all_roles_after_wipe"] = false,
                    ["micro_displays_locked"] = true,
                    ["auto_current"] = true,
                    ["auto_hide_menu"] = {
                        ["left"] = true,
                        ["right"] = false,
                    },
                    ["tooltip"] = {
                        ["n_abilities"] = 3,
                        ["n_enemies"] = 3,
                    },
                    ["clickthrough_window"] = false,
                    ["hide_in_combat"] = false,
                    ["posicao"] = {
                        ["normal"] = {
                            ["y"] = -538.0547370910645,
                            ["x"] = 604.1561279296875,
                            ["w"] = 182.7776947021484,
                            ["h"] = 107.4443588256836,
                        },
                        ["solo"] = {
                            ["y"] = 2,
                            ["x"] = 1,
                            ["w"] = 300,
                            ["h"] = 200,
                        },
                    },
                    ["fontstrings_text3_anchor"] = 38,
                    ["fontstrings_text_limit_offset"] = -10,
                    ["wallpaper"] = {
                        ["enabled"] = false,
                        ["overlay"] = {
                            1,
                            1,
                            1,
                            1,
                        },
                        ["texcoord"] = {
                            0,
                            1,
                            0,
                            0.7,
                        },
                        ["anchor"] = "all",
                        ["height"] = 114.042518615723,
                        ["level"] = 2,
                        ["alpha"] = 0.5,
                        ["width"] = 283.000183105469,
                    },
                    ["stretch_button_side"] = 1,
                    ["titlebar_height"] = 16,
                    ["bg_g"] = 0.2352941334247589,
                    ["menu_icons_color"] = {
                        1,
                        1,
                        1,
                    },
                    ["titlebar_texture_color"] = {
                        0.2,
                        0.2,
                        0.2,
                        0.8,
                    },
                },
                {
                    ["__pos"] = {
                        ["normal"] = {
                            ["y"] = -538.0547370910645,
                            ["x"] = 786.93359375,
                            ["w"] = 182.7776947021484,
                            ["h"] = 107.4443588256836,
                        },
                        ["solo"] = {
                            ["y"] = 2,
                            ["x"] = 1,
                            ["w"] = 300,
                            ["h"] = 200,
                        },
                    },
                    ["hide_in_combat_type"] = 1,
                    ["menu_icons_size"] = 0.82,
                    ["titlebar_shown"] = false,
                    ["menu_anchor"] = {
                        20,
                        0,
                        ["side"] = 2,
                    },
                    ["bg_r"] = 0.2431372702121735,
                    ["fullborder_size"] = 0.5,
                    ["hide_out_of_combat"] = false,
                    ["color_buttons"] = {
                        1,
                        1,
                        1,
                        1,
                    },
                    ["toolbar_icon_file"] = "Interface\\AddOns\\Details\\images\\toolbar_icons_2_shadow",
                    ["micro_displays_locked"] = true,
                    ["use_auto_align_multi_fontstrings"] = true,
                    ["rowareaborder_shown"] = false,
                    ["switch_all_roles_in_combat"] = false,
                    ["clickthrough_toolbaricons"] = false,
                    ["clickthrough_rows"] = false,
                    ["titlebar_texture"] = "Details Serenity",
                    ["ignore_mass_showhide"] = false,
                    ["plugins_grow_direction"] = 1,
                    ["icon_desaturated"] = false,
                    ["switch_damager"] = false,
                    ["micro_displays_side"] = 2,
                    ["window_scale"] = 1,
                    ["attribute_icon_size"] = 0,
                    ["hide_icon"] = true,
                    ["toolbar_side"] = 1,
                    ["fullborder_color"] = {
                        0,
                        0,
                        0,
                        1,
                    },
                    ["menu_icons_alpha"] = 0.92,
                    ["bg_b"] = 0.2588235437870026,
                    ["switch_healer_in_combat"] = false,
                    ["color"] = {
                        0.1215686351060867,
                        0.1176470667123795,
                        0.1294117718935013,
                        0,
                    },
                    ["hide_on_context"] = {
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                    },
                    ["desaturated_menu"] = false,
                    ["use_multi_fontstrings"] = true,
                    ["__was_opened"] = true,
                    ["fontstrings_text_limit_offset"] = -10,
                    ["total_bar"] = {
                        ["enabled"] = false,
                        ["only_in_group"] = true,
                        ["icon"] = "Interface\\ICONS\\INV_Sigil_Thorim",
                        ["color"] = {
                            1,
                            1,
                            1,
                        },
                    },
                    ["skin"] = "Minimalistic",
                    ["backdrop_texture"] = "Details Ground",
                    ["following"] = {
                        ["bar_color"] = {
                            1,
                            1,
                            1,
                        },
                        ["enabled"] = true,
                        ["text_color"] = {
                            1,
                            1,
                            1,
                        },
                    },
                    ["bars_inverted"] = false,
                    ["switch_healer"] = false,
                    ["fontstrings_text2_anchor"] = 73,
                    ["menu_icons"] = {
                        true,
                        true,
                        true,
                        true,
                        true,
                        false,
                        ["space"] = -2,
                        ["shadow"] = false,
                    },
                    ["clickthrough_window"] = false,
                    ["attribute_text"] = {
                        ["enabled"] = true,
                        ["shadow"] = false,
                        ["side"] = 1,
                        ["text_size"] = 11,
                        ["custom_text"] = "{name}",
                        ["show_timer_arena"] = true,
                        ["text_face"] = "Accidental Presidency",
                        ["show_timer_always"] = true,
                        ["text_color"] = {
                            1,
                            1,
                            1,
                            1,
                        },
                        ["anchor"] = {
                            -17,
                            2,
                        },
                        ["enable_custom_text"] = false,
                        ["show_timer"] = true,
                        ["show_timer_bg"] = true,
                    },
                    ["bars_sort_direction"] = 1,
                    ["switch_tank_in_combat"] = false,
                    ["StatusBarSaved"] = {
                        ["options"] = {
                            ["DETAILS_STATUSBAR_PLUGIN_PDPS"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["textXMod"] = 0,
                                ["textFace"] = "Accidental Presidency",
                                ["textAlign"] = 3,
                                ["textStyle"] = 2,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                            ["DETAILS_STATUSBAR_PLUGIN_PSEGMENT"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["segmentType"] = 2,
                                ["textFace"] = "Accidental Presidency",
                                ["textXMod"] = 0,
                                ["textAlign"] = 1,
                                ["textStyle"] = 2,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                            ["DETAILS_STATUSBAR_PLUGIN_CLOCK"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["textFace"] = "Accidental Presidency",
                                ["textXMod"] = 6,
                                ["textAlign"] = 2,
                                ["textStyle"] = 2,
                                ["timeType"] = 1,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                        },
                        ["right"] = "DETAILS_STATUSBAR_PLUGIN_PDPS",
                        ["left"] = "DETAILS_STATUSBAR_PLUGIN_PSEGMENT",
                        ["center"] = "DETAILS_STATUSBAR_PLUGIN_CLOCK",
                    },
                    ["version"] = 3,
                    ["__snapH"] = true,
                    ["instance_button_anchor"] = {
                        -27,
                        1,
                    },
                    ["bg_alpha"] = 0,
                    ["fontstrings_text4_anchor"] = 0,
                    ["__locked"] = true,
                    ["menu_alpha"] = {
                        ["enabled"] = false,
                        ["onenter"] = 1,
                        ["iconstoo"] = true,
                        ["ignorebars"] = false,
                        ["onleave"] = 1,
                    },
                    ["show_statusbar"] = false,
                    ["switch_all_roles_after_wipe"] = false,
                    ["grab_on_top"] = false,
                    ["rowareaborder_size"] = 0.5,
                    ["clickthrough_incombatonly"] = true,
                    ["__snap"] = {
                        1,
                        [3] = 3,
                    },
                    ["skin_custom"] = "",
                    ["hide_in_combat_alpha"] = 0,
                    ["__snapV"] = false,
                    ["rounded_corner_enabled"] = false,
                    ["libwindow"] = {
                        ["y"] = 8.223082542419434,
                        ["x"] = -188.34423828125,
                        ["point"] = "BOTTOMRIGHT",
                        ["scale"] = 1,
                    },
                    ["statusbar_info"] = {
                        ["alpha"] = 0,
                        ["overlay"] = {
                            0.1215686351060867,
                            0.1176470667123795,
                            0.1294117718935013,
                        },
                    },
                    ["bars_grow_direction"] = 1,
                    ["menu_anchor_down"] = {
                        16,
                        -3,
                    },
                    ["row_show_animation"] = {
                        ["anim"] = "Fade",
                        ["options"] = {
                        },
                    },
                    ["rowareaborder_color"] = {
                        0,
                        0,
                        0,
                        1,
                    },
                    ["strata"] = "LOW",
                    ["switch_damager_in_combat"] = false,
                    ["row_info"] = {
                        ["show_arena_role_icon"] = false,
                        ["spec_file"] = "Interface\\AddOns\\Details\\images\\spec_icons_normal",
                        ["textL_outline"] = false,
                        ["row_offsets"] = {
                            ["top"] = 0,
                            ["right"] = 0,
                            ["left"] = 0,
                            ["bottom"] = 0,
                        },
                        ["textR_outline_small"] = true,
                        ["textL_outline_small"] = true,
                        ["percent_type"] = 1,
                        ["fixed_text_color"] = {
                            1,
                            1,
                            1,
                        },
                        ["textL_offset"] = 0,
                        ["text_yoffset"] = 0,
                        ["texture_background_class_color"] = false,
                        ["start_after_icon"] = false,
                        ["font_face_file"] = "Interface\\Addons\\Plater\\fonts\\Accidental Presidency.ttf",
                        ["faction_icon_size_offset"] = -10,
                        ["textL_enable_custom_text"] = false,
                        ["textL_custom_text"] = "{data1}. {data3}{data2}",
                        ["font_size"] = 10,
                        ["models"] = {
                            ["upper_model"] = "Spells\\AcidBreath_SuperGreen.M2",
                            ["lower_model"] = "World\\EXPANSION02\\DOODADS\\Coldarra\\COLDARRALOCUS.m2",
                            ["upper_alpha"] = 0.5,
                            ["lower_enabled"] = false,
                            ["lower_alpha"] = 0.1,
                            ["upper_enabled"] = false,
                        },
                        ["textL_outline_small_color"] = {
                            0,
                            0,
                            0,
                            1,
                        },
                        ["show_faction_icon"] = false,
                        ["textL_translit_text"] = false,
                        ["height"] = 18,
                        ["texture_file"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Statusbar_Clean",
                        ["icon_size_offset"] = 0,
                        ["textR_show_data"] = {
                            true,
                            true,
                            false,
                        },
                        ["icon_mask"] = "",
                        ["overlay_color"] = {
                            0.7,
                            0.7,
                            0.7,
                            0,
                        },
                        ["textR_outline"] = false,
                        ["icon_file"] = "",
                        ["arena_role_icon_size_offset"] = -10,
                        ["icon_grayscale"] = false,
                        ["texture_custom"] = "",
                        ["use_spec_icons"] = false,
                        ["textR_enable_custom_text"] = false,
                        ["texture_background"] = "Clean",
                        ["fixed_texture_color"] = {
                            0,
                            0,
                            0,
                        },
                        ["textL_show_number"] = false,
                        ["textR_outline_small_color"] = {
                            0,
                            0,
                            0,
                            1,
                        },
                        ["textR_class_colors"] = false,
                        ["textR_custom_text"] = "{data1} ({data2}, {data3}%)",
                        ["texture"] = "Clean",
                        ["texture_highlight"] = "Interface\\FriendsFrame\\UI-FriendsList-Highlight",
                        ["texture_background_file"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Statusbar_Clean",
                        ["overlay_texture"] = "Clean",
                        ["fixed_texture_background_color"] = {
                            0,
                            0,
                            0,
                            0.150228589773178,
                        },
                        ["space"] = {
                            ["right"] = 0,
                            ["left"] = 0,
                            ["between"] = 2,
                        },
                        ["textL_class_colors"] = false,
                        ["alpha"] = 1,
                        ["no_icon"] = true,
                        ["icon_offset"] = {
                            0,
                            0,
                        },
                        ["textR_bracket"] = "(",
                        ["font_face"] = "Accidental Presidency",
                        ["texture_class_colors"] = true,
                        ["texture_custom_file"] = "Interface\\",
                        ["fast_ps_update"] = false,
                        ["textR_separator"] = "NONE",
                        ["backdrop"] = {
                            ["color"] = {
                                1,
                                1,
                                1,
                                1,
                            },
                            ["size"] = 12,
                            ["enabled"] = false,
                            ["texture"] = "Details BarBorder 2",
                        },
                    },
                    ["switch_tank"] = false,
                    ["auto_current"] = true,
                    ["auto_hide_menu"] = {
                        ["left"] = true,
                        ["right"] = false,
                    },
                    ["show_sidebars"] = false,
                    ["tooltip"] = {
                        ["n_abilities"] = 3,
                        ["n_enemies"] = 3,
                    },
                    ["hide_in_combat"] = false,
                    ["posicao"] = {
                        ["normal"] = {
                            ["y"] = -538.0547370910645,
                            ["x"] = 786.93359375,
                            ["w"] = 182.7776947021484,
                            ["h"] = 107.4443588256836,
                        },
                        ["solo"] = {
                            ["y"] = 2,
                            ["x"] = 1,
                            ["w"] = 300,
                            ["h"] = 200,
                        },
                    },
                    ["fullborder_shown"] = false,
                    ["fontstrings_text3_anchor"] = 38,
                    ["wallpaper"] = {
                        ["enabled"] = false,
                        ["overlay"] = {
                            1,
                            1,
                            1,
                            1,
                        },
                        ["texcoord"] = {
                            0,
                            1,
                            0,
                            0.7,
                        },
                        ["height"] = 114.042518615723,
                        ["anchor"] = "all",
                        ["level"] = 2,
                        ["alpha"] = 0.5,
                        ["width"] = 283.000183105469,
                    },
                    ["stretch_button_side"] = 1,
                    ["titlebar_height"] = 16,
                    ["bg_g"] = 0.2352941334247589,
                    ["menu_icons_color"] = {
                        1,
                        1,
                        1,
                    },
                    ["titlebar_texture_color"] = {
                        0.2,
                        0.2,
                        0.2,
                        0.8,
                    },
                },
                {
                    ["__pos"] = {
                        ["normal"] = {
                            ["y"] = -538.0547370910645,
                            ["x"] = 969.71142578125,
                            ["w"] = 182.7776947021484,
                            ["h"] = 107.4443588256836,
                        },
                        ["solo"] = {
                            ["y"] = 2,
                            ["x"] = 1,
                            ["w"] = 300,
                            ["h"] = 200,
                        },
                    },
                    ["hide_in_combat_type"] = 1,
                    ["menu_icons_size"] = 0.82,
                    ["titlebar_shown"] = false,
                    ["menu_anchor"] = {
                        20,
                        0,
                        ["side"] = 2,
                    },
                    ["bg_r"] = 0.2431372702121735,
                    ["fullborder_size"] = 0.5,
                    ["hide_out_of_combat"] = false,
                    ["color_buttons"] = {
                        1,
                        1,
                        1,
                        1,
                    },
                    ["toolbar_icon_file"] = "Interface\\AddOns\\Details\\images\\toolbar_icons_2_shadow",
                    ["micro_displays_locked"] = true,
                    ["use_auto_align_multi_fontstrings"] = true,
                    ["rowareaborder_shown"] = false,
                    ["switch_all_roles_in_combat"] = false,
                    ["clickthrough_toolbaricons"] = false,
                    ["clickthrough_rows"] = false,
                    ["titlebar_texture"] = "Details Serenity",
                    ["ignore_mass_showhide"] = false,
                    ["plugins_grow_direction"] = 1,
                    ["icon_desaturated"] = false,
                    ["switch_damager"] = false,
                    ["micro_displays_side"] = 2,
                    ["window_scale"] = 1,
                    ["attribute_icon_size"] = 0,
                    ["hide_icon"] = true,
                    ["toolbar_side"] = 1,
                    ["fullborder_color"] = {
                        0,
                        0,
                        0,
                        1,
                    },
                    ["menu_icons_alpha"] = 0.92,
                    ["bg_b"] = 0.2588235437870026,
                    ["switch_healer_in_combat"] = false,
                    ["color"] = {
                        0.1215686351060867,
                        0.1176470667123795,
                        0.1294117718935013,
                        0,
                    },
                    ["hide_on_context"] = {
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                        {
                            ["enabled"] = false,
                            ["inverse"] = false,
                            ["value"] = 100,
                        },
                    },
                    ["desaturated_menu"] = false,
                    ["use_multi_fontstrings"] = true,
                    ["__was_opened"] = true,
                    ["fontstrings_text_limit_offset"] = -10,
                    ["total_bar"] = {
                        ["enabled"] = false,
                        ["only_in_group"] = true,
                        ["icon"] = "Interface\\ICONS\\INV_Sigil_Thorim",
                        ["color"] = {
                            1,
                            1,
                            1,
                        },
                    },
                    ["skin"] = "Minimalistic",
                    ["backdrop_texture"] = "Details Ground",
                    ["following"] = {
                        ["bar_color"] = {
                            1,
                            1,
                            1,
                        },
                        ["enabled"] = true,
                        ["text_color"] = {
                            1,
                            1,
                            1,
                        },
                    },
                    ["bars_inverted"] = false,
                    ["switch_healer"] = false,
                    ["fontstrings_text2_anchor"] = 73,
                    ["menu_icons"] = {
                        true,
                        true,
                        true,
                        true,
                        true,
                        false,
                        ["space"] = -2,
                        ["shadow"] = false,
                    },
                    ["clickthrough_window"] = false,
                    ["attribute_text"] = {
                        ["enabled"] = true,
                        ["shadow"] = false,
                        ["side"] = 1,
                        ["text_size"] = 11,
                        ["custom_text"] = "{name}",
                        ["show_timer_arena"] = true,
                        ["text_face"] = "Accidental Presidency",
                        ["show_timer_always"] = true,
                        ["text_color"] = {
                            1,
                            1,
                            1,
                            1,
                        },
                        ["anchor"] = {
                            -17,
                            2,
                        },
                        ["enable_custom_text"] = false,
                        ["show_timer"] = true,
                        ["show_timer_bg"] = true,
                    },
                    ["bars_sort_direction"] = 1,
                    ["switch_tank_in_combat"] = false,
                    ["StatusBarSaved"] = {
                        ["options"] = {
                            ["DETAILS_STATUSBAR_PLUGIN_PDPS"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["textXMod"] = 0,
                                ["textFace"] = "Accidental Presidency",
                                ["textAlign"] = 3,
                                ["textStyle"] = 2,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                            ["DETAILS_STATUSBAR_PLUGIN_PSEGMENT"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["segmentType"] = 2,
                                ["textFace"] = "Accidental Presidency",
                                ["textXMod"] = 0,
                                ["textAlign"] = 1,
                                ["textStyle"] = 2,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                            ["DETAILS_STATUSBAR_PLUGIN_CLOCK"] = {
                                ["textColor"] = {
                                    1,
                                    1,
                                    1,
                                    1,
                                },
                                ["textFace"] = "Accidental Presidency",
                                ["textXMod"] = 6,
                                ["textAlign"] = 2,
                                ["textStyle"] = 2,
                                ["timeType"] = 1,
                                ["textSize"] = 10,
                                ["textYMod"] = 1,
                            },
                        },
                        ["right"] = "DETAILS_STATUSBAR_PLUGIN_PDPS",
                        ["left"] = "DETAILS_STATUSBAR_PLUGIN_PSEGMENT",
                        ["center"] = "DETAILS_STATUSBAR_PLUGIN_CLOCK",
                    },
                    ["version"] = 3,
                    ["__snapH"] = true,
                    ["instance_button_anchor"] = {
                        -27,
                        1,
                    },
                    ["bg_alpha"] = 0,
                    ["fontstrings_text4_anchor"] = 0,
                    ["__locked"] = false,
                    ["menu_alpha"] = {
                        ["enabled"] = false,
                        ["onenter"] = 1,
                        ["iconstoo"] = true,
                        ["ignorebars"] = false,
                        ["onleave"] = 1,
                    },
                    ["show_statusbar"] = false,
                    ["switch_all_roles_after_wipe"] = false,
                    ["grab_on_top"] = false,
                    ["rowareaborder_size"] = 0.5,
                    ["clickthrough_incombatonly"] = true,
                    ["__snap"] = {
                        2,
                    },
                    ["skin_custom"] = "",
                    ["hide_in_combat_alpha"] = 0,
                    ["__snapV"] = false,
                    ["rounded_corner_enabled"] = false,
                    ["libwindow"] = {
                        ["y"] = 8.223082542419434,
                        ["x"] = -5.56640625,
                        ["point"] = "BOTTOMRIGHT",
                        ["scale"] = 1,
                    },
                    ["statusbar_info"] = {
                        ["alpha"] = 0,
                        ["overlay"] = {
                            0.1215686351060867,
                            0.1176470667123795,
                            0.1294117718935013,
                        },
                    },
                    ["bars_grow_direction"] = 1,
                    ["menu_anchor_down"] = {
                        16,
                        -3,
                    },
                    ["row_show_animation"] = {
                        ["anim"] = "Fade",
                        ["options"] = {
                        },
                    },
                    ["rowareaborder_color"] = {
                        0,
                        0,
                        0,
                        1,
                    },
                    ["strata"] = "LOW",
                    ["switch_damager_in_combat"] = false,
                    ["row_info"] = {
                        ["show_arena_role_icon"] = false,
                        ["spec_file"] = "Interface\\AddOns\\Details\\images\\spec_icons_normal",
                        ["textL_outline"] = false,
                        ["row_offsets"] = {
                            ["top"] = 0,
                            ["right"] = 0,
                            ["left"] = 0,
                            ["bottom"] = 0,
                        },
                        ["textR_outline_small"] = true,
                        ["textL_outline_small"] = true,
                        ["percent_type"] = 1,
                        ["fixed_text_color"] = {
                            1,
                            1,
                            1,
                        },
                        ["textL_offset"] = 0,
                        ["text_yoffset"] = 0,
                        ["texture_background_class_color"] = false,
                        ["start_after_icon"] = false,
                        ["font_face_file"] = "Interface\\Addons\\Plater\\fonts\\Accidental Presidency.ttf",
                        ["faction_icon_size_offset"] = -10,
                        ["textL_enable_custom_text"] = false,
                        ["textL_custom_text"] = "{data1}. {data3}{data2}",
                        ["font_size"] = 10,
                        ["models"] = {
                            ["upper_model"] = "Spells\\AcidBreath_SuperGreen.M2",
                            ["lower_model"] = "World\\EXPANSION02\\DOODADS\\Coldarra\\COLDARRALOCUS.m2",
                            ["upper_alpha"] = 0.5,
                            ["lower_enabled"] = false,
                            ["lower_alpha"] = 0.1,
                            ["upper_enabled"] = false,
                        },
                        ["textL_outline_small_color"] = {
                            0,
                            0,
                            0,
                            1,
                        },
                        ["show_faction_icon"] = false,
                        ["textL_translit_text"] = false,
                        ["height"] = 18,
                        ["texture_file"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Statusbar_Clean",
                        ["icon_size_offset"] = 0,
                        ["textR_show_data"] = {
                            true,
                            true,
                            false,
                        },
                        ["icon_mask"] = "",
                        ["overlay_color"] = {
                            0.7,
                            0.7,
                            0.7,
                            0,
                        },
                        ["textR_outline"] = false,
                        ["icon_file"] = "",
                        ["arena_role_icon_size_offset"] = -10,
                        ["icon_grayscale"] = false,
                        ["texture_custom"] = "",
                        ["use_spec_icons"] = false,
                        ["textR_enable_custom_text"] = false,
                        ["texture_background"] = "Clean",
                        ["fixed_texture_color"] = {
                            0,
                            0,
                            0,
                        },
                        ["textL_show_number"] = false,
                        ["textR_outline_small_color"] = {
                            0,
                            0,
                            0,
                            1,
                        },
                        ["textR_class_colors"] = false,
                        ["textR_custom_text"] = "{data1} ({data2}, {data3}%)",
                        ["texture"] = "Clean",
                        ["texture_highlight"] = "Interface\\FriendsFrame\\UI-FriendsList-Highlight",
                        ["texture_background_file"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Statusbar_Clean",
                        ["overlay_texture"] = "Clean",
                        ["fixed_texture_background_color"] = {
                            0,
                            0,
                            0,
                            0.150228589773178,
                        },
                        ["space"] = {
                            ["right"] = 0,
                            ["left"] = 0,
                            ["between"] = 2,
                        },
                        ["textL_class_colors"] = false,
                        ["alpha"] = 1,
                        ["no_icon"] = true,
                        ["icon_offset"] = {
                            0,
                            0,
                        },
                        ["textR_bracket"] = "(",
                        ["font_face"] = "Accidental Presidency",
                        ["texture_class_colors"] = true,
                        ["texture_custom_file"] = "Interface\\",
                        ["fast_ps_update"] = false,
                        ["textR_separator"] = "NONE",
                        ["backdrop"] = {
                            ["color"] = {
                                1,
                                1,
                                1,
                                1,
                            },
                            ["size"] = 12,
                            ["enabled"] = false,
                            ["texture"] = "Details BarBorder 2",
                        },
                    },
                    ["switch_tank"] = false,
                    ["auto_current"] = true,
                    ["auto_hide_menu"] = {
                        ["left"] = true,
                        ["right"] = false,
                    },
                    ["show_sidebars"] = false,
                    ["tooltip"] = {
                        ["n_abilities"] = 3,
                        ["n_enemies"] = 3,
                    },
                    ["hide_in_combat"] = false,
                    ["posicao"] = {
                        ["normal"] = {
                            ["y"] = -538.0547370910645,
                            ["x"] = 969.71142578125,
                            ["w"] = 182.7776947021484,
                            ["h"] = 107.4443588256836,
                        },
                        ["solo"] = {
                            ["y"] = 2,
                            ["x"] = 1,
                            ["w"] = 300,
                            ["h"] = 200,
                        },
                    },
                    ["fullborder_shown"] = false,
                    ["fontstrings_text3_anchor"] = 38,
                    ["wallpaper"] = {
                        ["enabled"] = false,
                        ["overlay"] = {
                            1,
                            1,
                            1,
                            1,
                        },
                        ["texcoord"] = {
                            0,
                            1,
                            0,
                            0.7,
                        },
                        ["height"] = 114.042518615723,
                        ["anchor"] = "all",
                        ["level"] = 2,
                        ["alpha"] = 0.5,
                        ["width"] = 283.000183105469,
                    },
                    ["stretch_button_side"] = 1,
                    ["titlebar_height"] = 16,
                    ["bg_g"] = 0.2352941334247589,
                    ["menu_icons_color"] = {
                        1,
                        1,
                        1,
                    },
                    ["titlebar_texture_color"] = {
                        0.2,
                        0.2,
                        0.2,
                        0.8,
                    },
                },
            },
            ["auto_swap_to_dynamic_overall"] = false,
            ["time_type_original"] = 2,
            ["player_details_window"] = {
                ["scale"] = 1,
                ["skin"] = "ElvUI",
                ["bar_texture"] = "Skyline",
            },
            ["class_icons_small"] = "Interface\\AddOns\\Details\\images\\classes_small",
            ["force_activity_time_pvp"] = true,
            ["death_tooltip_width"] = 350,
            ["death_tooltip_texture"] = "Details Serenity",
            ["disable_reset_button"] = false,
            ["animate_scroll"] = false,
            ["realtime_dps_meter"] = {
                ["enabled"] = false,
                ["font_color"] = {
                    1,
                    1,
                    1,
                    1,
                },
                ["arena_enabled"] = true,
                ["font_shadow"] = "NONE",
                ["font_size"] = 18,
                ["mythic_dungeon_enabled"] = false,
                ["sample_size"] = 3,
                ["frame_settings"] = {
                    ["show_title"] = true,
                    ["strata"] = "LOW",
                    ["point"] = "TOP",
                    ["scale"] = 1,
                    ["width"] = 300,
                    ["y"] = -110,
                    ["x"] = 0,
                    ["backdrop_color"] = {
                        0,
                        0,
                        0,
                        0.2,
                    },
                    ["locked"] = true,
                    ["height"] = 23,
                },
                ["font_face"] = "Friz Quadrata TT",
                ["text_offset"] = 2,
                ["update_interval"] = 0.3,
                ["options_frame"] = {
                },
            },
            ["disable_stretch_from_toolbar"] = false,
            ["default_bg_alpha"] = 0.5,
            ["profile_save_pos"] = true,
        }

    local function detailsCallback(savedVariables, profileName, settings)
        if _G["_detalhes"] then
            _G["_detalhes"].always_use_profile = true
            _G["_detalhes"].always_use_profile_name = profileName
        end
    end

    AddonProfileManager:ApplySettings("Details", "_detalhes_global", detailsSettings, detailsCallback)
end
