name: Update Version, Tag, and Release
on:
  push:
    branches:
      - master
jobs:
  update-version-tag-and-release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get current version from TOC
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=## Version: ).*' PeaversUI.toc)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Update TOC version
        id: update_toc
        run: |
          NEW_VERSION="1.0.${{ github.run_number }}"
          sed -i "s/^## Version: .*$/## Version: $NEW_VERSION/" PeaversUI.toc
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit TOC changes
        run: |
          git config user.name "Chris Turner"
          git config user.email "peavers@gmail.com"
          git add PeaversUI.toc
          git commit -m "chore: Update TOC version to ${{ steps.update_toc.outputs.new_version }}"
          git push

      - name: Create and push tag
        run: |
          TAG_NAME="PeaversUI-${{ steps.update_toc.outputs.new_version }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.update_toc.outputs.new_version }}
          release_name: Release ${{ steps.update_toc.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Create Package and Release on CurseForge
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          version: ${{ steps.update_toc.outputs.new_version }}
