name: Update Version, Tag, and Release

on:
  push:
    branches:
      - master

jobs:
  update-version-tag-and-release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the latest release version
        id: get_latest_release
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          if [[ -z "$latest_tag" ]]; then
            new_version="1.0.0"
          else
            new_version=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
          fi
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "Latest version is $new_version"

      - name: Get current version from TOC
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=## Version: ).*' PeaversUI.toc)
          echo "version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Update TOC version
        id: update_toc
        run: |
          sed -i "s/^## Version: .*$/## Version: ${{ env.new_version }}/" PeaversUI.toc
          echo "new_version=${{ env.new_version }}" >> $GITHUB_ENV

      - name: Commit TOC changes
        run: |
          git config user.name "Chris Turner"
          git config user.email "peavers@gmail.com"
          git add PeaversUI.toc
          git commit -m "chore: Update TOC version to ${{ env.new_version }}"
          git push

      - name: Create and push tag
        run: |
          TAG_NAME="PeaversUI-${{ env.new_version }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_version }}
          release_name: Release ${{ env.new_version }}
          draft: false
          prerelease: false

      - name: Create Package and Release on CurseForge
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          version: ${{ env.new_version }}
