name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create and push tag
        run: |
          TAG_NAME="PeaversUI-1.0.${{ github.run_number }}"
          git config user.name "Chris Turner"
          git config user.email "peavers@gmail.com"
          git tag $TAG_NAME
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin $TAG_NAME
